### ISSUE TITLE
Står berre loading.

### ISSUE THREAD

**Issue by petrepa** [ottopaulsen/MMM-NesteBussAtB#3]
Hei! Supert at nokon har teke steget og fått laga ein modul for AtB. Til no har eg berre brukt iFrame og vist AtB sin nettstad. Får foreløpig ikkje modulen til å fungere skikkelig. Står berre "loading...". Klarer ikkje å sjå kva som evt. kan vere feil i config.

Her er det eg har:
`{
        module: 'MMM-NesteBussAtB',
        position: 'upper_third',
        config: {
            showIcon: true, // Bus icon in front of row
            showNumber: true, // Bus number
            showFrom: true, // Bus stop name
            showTo: true, // Bus destination
            showMin: true, // "min" text after minutes
            size: "medium", // Text size, for example small, medium or large
            stopIds: [16011404, 16010404], // See https://www.atb.no/holdeplassoversikt/
            maxCount: 2, // Max number of next buses per route
            maxMinutes: 45 // Do not show buses more then this minutes into the future
        	}
        },`

Nokon som kan hjelpe?

**Comment by petrepa** [comment]
Fekk fiksa det! Krevde berre ein omstart om eg ikkje tek alt for feil, hehe

**Comment by ottopaulsen** [comment]
Jeg har oppgradert nå, så den bruker AtB sin soap service i stedet for den jeg brukte før (som ble tatt ned).
