### ISSUE TITLE
Backend/API has been shut down and moved

### ISSUE THREAD

**Issue by marviks** [ottopaulsen/MMM-NesteBussAtB#4]
The source/backend/API for this module has moved or been shut down. Is there any chance you would be willing to update the module and support the new source?

**Comment by ottopaulsen** [comment]
Sure. Will try. Do you know anything about it? What can I use instead?

**Comment by ottopaulsen** [comment]
This is fixed now. I am using the Stop Monitoring Service from AtB directly. It is faster too. Haven´t tested too much...

**Comment by marviks** [comment]
Hey, this is great! I will test it this week. I know that busskartet.no and busskart.no has some rest-apis. They might be willing to share access if asked, and if SMS isnt working out. Thanks for looking into this.
